---
  - name: Swarm Security Group
    ec2_group:
      name: "{{ swarm_security_group_name }}" 
      description: "swarm security group"
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      vpc_id: "{{ aws_vpc_id }}"
      rules:
        - proto: tcp
          from_port: "{{ ssh_port }}"
          to_port: "{{ ssh_port }}"
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: "{{ swarm_manager_port }}"
          to_port: "{{ swarm_manager_port }}"
          group_name: "{{ swarm_security_group_name }}"
        - proto: -1
          group_name: "{{ swarm_security_group_name }}"
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: udp
          from_port: "{{ flanel_overlay_network_port }}"
          to_port: "{{ flanel_overlay_network_port }}"
          group_name: "{{ swarm_security_group_name }}"
        - proto: tcp
          from_port: 0
          to_port: 65535
          cidr_ip: 0.0.0.0/0
