---
  - name: Swarm Security Group
    ec2_group:
      name: "{{ swarm_security_group_name }}"
      description: "swarm security group"
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      vpc_id: "{{ aws_vpc_id }}"
      rules:
        - proto: all
          from_port: -1
          to_port: -1
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          from_port: -1
          to_port: -1
          cidr_ip: 0.0.0.0/0
