---
- name: CLI tests
  shell: go test ./cmd/amp/cli
  args:
    chdir: "{{ amp_base_directory }}/amp/"
  environment:
    GOPATH: /go
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/go/bin"
  register: clitests
  no_log: true
  ignore_errors: true
  when: inventory_hostname == groups['swarm_mgr'][0]

- debug: var=clitests.stdout_lines
  when: clitests|failed
