---
- name: cleanup vendor
  shell: test -d vendor && rm -rf vendor
  args:
    chdir: "{{ amp_base_directory }}/amp/"
  ignore_errors: true
- name: glide install
  shell: glide install
  args:
    chdir: "{{ amp_base_directory }}/amp/"
  environment:
    GOPATH: /go
    PATH: "{{ ansible_env.PATH }}:/go/bin"
- name: make install
  shell: make install
  args:
    chdir: "{{ amp_base_directory }}/amp/"
  environment:
    GOPATH: /go
    PATH: "{{ ansible_env.PATH }}:/go/bin"
