---
  - name: prepare amp directory
    file: path="{{ amp_base_directory }}/amp" state=directory mode=0755
  - name: prepare docker config directory
    file: path=/root/.docker state=directory owner=root mode=0700
  - name: credentials for AMP images
    template: src=docker-config.json dest=/root/.docker/config.json
    when: registry_auth is defined
